### ISSUE TITLE
incorrect command line option in help text

### ISSUE THREAD

**Issue by lorg** [Cymmetria/honeycomb#18]
When you type honeycomb integration configure syslog, you get the text:
"Error: [-] Parameters: 'to_phone' is missing (use --args to see all parameters)"
But the option name is actually --show_args. 
Should fix either the option name or the help text.

**Comment by omercnet** [comment]
should be an easy fix, can even edit in GitHub web interface, please submit a PR if you can

**Comment by WottatoParrior** [comment]
I would like to help with that.
I am just starting to contribute and i would like it if you pointed me at the right direction.
Thank you

**Comment by WottatoParrior** [comment]
I think i fixed it 🥇

**Comment by omercnet** [comment]
awesome, open a pull request from your fixed fork to us and I'll review it!
