### ISSUE TITLE
Documentation syntax errors

### ISSUE THREAD

**Issue by Sleeptime17** [Cymmetria/honeycomb#32]
![image](https://user-images.githubusercontent.com/33372824/43620633-68858b10-96dc-11e8-8483-61fee5ad2af0.png)

Note two things:
1. Honeycomb is capitalized. This persists throughout the page (http://honeycomb.cymmetria.com/en/master/cli.html#honeycomb-integration)

2. The default home path contains /docs/ for whatever reason (/home/docs/.config/honeycomb). This is obviously not the case, even in my system, but rather "docs" should be replaced by my username.

**Comment by Sleeptime17** [comment]
Fixed the first issue

**Comment by omercnet** [comment]
2 is being evaluated when the docs are getting compiled on RTD, need to see
if we can control the user name and change it to `user` so it at least
looks generic
