### ISSUE TITLE
config.json parameter type "file" not accepted

### ISSUE THREAD

**Issue by Sleeptime17** [Cymmetria/honeycomb#33]
"parameters": [
{
"type": "text",
"value": "username",
"label": "Authentication username",
"required": true
},
{
"type": "text",
"value": "password",
"label": "Authentication password",
"required": true
},
{
"type": "file",
"value": "dit",
"label": "DIT file (database for the LDAP server)"
}

This works on Mazerunner, but HC reports this as:

"Error: [-] Parameters: 'file' is not a valid type"

**Comment by omercnet** [comment]
Should be easy fix to add a parameter

What's the behavior like once the service gets the parameter?
You get a file object? Path? Stream?

**Comment by Sleeptime17** [comment]
The content as a string I believe.
I was adding it towards the end of the hackathon and tbh fell asleep in the middle when the last problem I encountered was that I can't open the file due to path issues (I only get the filename whereas the cwd isn't even where the file is). Needed to think of a solution and fell asleep.

**Comment by omercnet** [comment]
fixed by #68
